### ISSUE TITLE
Task::Biodiverse not needed for versions >3.1

### ISSUE THREAD

**Issue by shawnlaffan** [vmikk/biodiverse-docker#4]
This can be skipped for the docker file since it is using current head.  

https://github.com/vmikk/biodiverse-docker/blob/6eed589ab9609a1e57910d48357269f566bfe95a/Dockerfile#L125-L126

**Comment by vmikk** [comment]
Done. `Task::Biodiverse` dependency removed with [7fd5ffc](https://github.com/vmikk/biodiverse-docker/commit/7fd5ffcf661fa4dd28c2aac100bbe65894085aec).
